### ISSUE TITLE
Index error when number of samples is not a multiple of 10

### ISSUE THREAD

**Issue by kdolum** [nanograv/PTMCMCSampler#20]
I say `sampler.sample(x0, 128, SCAMweight=30, AMweight=15, DEweight=50)` and I get `IndexError: index 12 is out of bounds for axis 0 with size 12`.  12 is the quotient of 128 over 10.  It seems to be completely repeatable, giving an error for any number of samples that is not a multiple of 10.

**Comment by paulthebaker** [comment]
It looks like the issue comes from when the chain arrays get initialized at [PTMCMCSampler.py#L182](https://github.com/jellis18/PTMCMCSampler/blob/master/PTMCMCSampler/PTMCMCSampler.py#L182).  The default `thin` is 10.  The issue occurs whenever `Niter/thin` is not an integer ratio.  It looks like it would be solved by justing adding `1` to `N`.

**Comment by paulthebaker** [comment]
Adding `1` to `N` causes an extra unused index at the end of the arrays with `Niter/burn` is an integer ratio.  It seems the best thing to do is round:
```python
N = int(np.ceil(maxIter / thin))
```

**Comment by kdolum** [comment]
Fixed by #41.
